version: '3.9'
services:
  # Node App
  auth:
    container_name: auth
    build:
      context: microservice_auth
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - postgres
  # Postgresql
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: microservice_auth
    ports:
      - '5432:5432'
    networks:
      - app-net
    volumes:
      - pg_data:/data/db
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh

networks:
  app-net:
    driver: bridge
volumes:
  pg_data:
